CREATE TABLE Product (
    ProductID INT PRIMARY KEY,
    Name VARCHAR(100),
    ProductNumber VARCHAR(50),
    MakeFlag INT,
    FinishedGoodsFlag INT,
    Color VARCHAR(50),
    SafetyStockLevel INT,
    ReorderPoint INT,
    StandardCost DECIMAL(10,2),
    ListPrice DECIMAL(10,2),
    Size VARCHAR(50),
    SizeUnitMeasureCode VARCHAR(50),
    WeightUnitMeasureCode VARCHAR(50),
    Weight DECIMAL(10,2),
    DaysToManufacture INT,
    ProductLine VARCHAR(50),
    Class VARCHAR(50),
    Style VARCHAR(50),
    ProductSubcategoryID INT,
    ProductModelID INT,
    SellStartDate DATE,
    SellEndDate DATE,
    DiscontinuedDate DATE,
    rowguid VARCHAR(50),
    ModifiedDate TIMESTAMP
);
