CREATE TABLE SalesOrder (
    SalesOrderID INT PRIMARY KEY,
    RevisionNumber INT,
    OrderDate TIMESTAMP,
    DueDate TIMESTAMP,
    ShipDate TIMESTAMP,
    Status INT,
    OnlineOrderFlag INT,
    SalesOrderNumber VARCHAR(50),
    PurchaseOrderNumber VARCHAR(50),
    AccountNumber VARCHAR(50),
    CustomerID INT,
    SalesPersonID VARCHAR(50),
    TerritoryID INT,
    BillToAddressID INT,
    ShipToAddressID INT,
    ShipMethodID INT,
    CreditCardID VARCHAR(50),
    CreditCardApprovalCode VARCHAR(50),
    CurrencyRateID VARCHAR(50),
    SubTotal DECIMAL(10, 2),
    TaxAmt DECIMAL(10, 2),
    Freight DECIMAL(10, 2),
    TotalDue DECIMAL(10, 2),
    Comment VARCHAR(MAX),
    rowguid VARCHAR(50),
    ModifiedDate TIMESTAMP
);
